<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
        <RootNamespace>Norbert86</RootNamespace>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
        <AssemblyName>daemonapp</AssemblyName>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>Norbert86.Test</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>



    <ItemGroup>
        <None Update="$(MSBuildProjectDir)appsettings.Development.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>        
        <None Update="$(MSBuildProjectDir)appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="$(MSBuildProjectDir)**\*.yaml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </None>
    </ItemGroup>
    <Target Name="AfterPublishMessage" AfterTargets="Publish">
        <Message Text="Publish done!" Importance="high" />
    </Target>
        
    <ItemGroup>
        <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
        <PackageReference Include="NetDaemon.AppModel" Version="24.28.0" />
        <PackageReference Include="NetDaemon.Runtime" Version="24.28.0" />
        <PackageReference Include="NetDaemon.HassModel" Version="24.28.0" />
        <PackageReference Include="NetDaemon.Client" Version="24.28.0" />
        <PackageReference Include="NetDaemon.Extensions.Scheduling" Version="24.28.0" />
        <PackageReference Include="NetDaemon.Extensions.Logging" Version="24.28.0" />
        <PackageReference Include="NetDaemon.Extensions.Tts" Version="24.28.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
        <PackageReference Include="System.Reactive" Version="6.0.1" />
    </ItemGroup>
</Project>
